[package]
name = "bflb-rt"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
default = ["panic"]
panic = []  # To implement a default panic handler.
bl808_d0 = []
bl808_m0 = []
__dev = []
